#!/bin/sh

set -o errexit
set -o nounset

ROOT="$(git rev-parse --show-toplevel)"
DEPENDENCIES="$ROOT/DEPENDENCIES"

fail() {
  echo "$1" 1>&2
  exit 1
}

log() {
  echo "-- $1" 1>&2
}

# $1 = version
is_file_dependency() {
  echo "$1" | grep -Eq '^[a-f0-9]{64}$'
}

# $1 = path
checksum() {
  if command -v sha256sum > /dev/null
  then
    sha256sum "$1" | cut -d ' ' -f 1
  elif command -v shasum > /dev/null
  then
    shasum --algorithm 256 "$1" | cut -d ' ' -f 1
  elif command -v openssl > /dev/null
  then
    openssl dgst -sha256 "$1" | awk '{ print $NF }'
  else
    fail "Cannot find sha256sum, shasum, or openssl to compute checksums"
  fi
}

if [ ! -f "$DEPENDENCIES" ]
then
  fail "File not found: $DEPENDENCIES"
fi

DEPENDENCY="${1-}"
if [ -z "$DEPENDENCY" ]
then
  fail "Usage: $0 <dependency>"
fi

LINE="$(grep "^$DEPENDENCY " < "$DEPENDENCIES" || true)"
if [ -z "$LINE" ]
then
  fail "Unknown dependency: $DEPENDENCY"
fi

NAME="$(echo "$LINE" | cut -d ' ' -f 1)"
URL="$(echo "$LINE" | cut -d ' ' -f 2)"
VERSION="$(echo "$LINE" | cut -d ' ' -f 3)"
if [ -z "$NAME" ] || [ -z "$URL" ] || [ -z "$VERSION" ]
then
  fail "Invalid dependency definition: $DEPENDENCY"
fi

TMP="$(mktemp -d -t vendorpull-clone-XXXXXX)"
log "Setting up temporary directory at $TMP..."
clean() { rm -rf "$TMP"; }
trap clean EXIT

if is_file_dependency "$VERSION"
then
  log "Downloading $URL into $TMP/$NAME"
  mkdir -p "$(dirname "$TMP/$NAME")"
  curl --fail --silent --show-error --location --output "$TMP/$NAME" "$URL"
  NEW_VERSION="$(checksum "$TMP/$NAME")"
else
  log "Fetching the tip of $URL into $TMP/$NAME"
  git clone --depth 1 --jobs 8 "$URL" "$TMP/$NAME"

  # Try to determine the tag, otherwise the commit hash
  NEW_VERSION="$(git -C "$TMP/$NAME" describe --tags --exact-match HEAD 2>/dev/null \
    || git -C "$TMP/$NAME" rev-parse HEAD)"
fi

log "Upgrading $NAME to $NEW_VERSION"
awk -v name="$NAME" -v version="$NEW_VERSION" \
  '$1 == name {$3 = version} {print}' \
  "$DEPENDENCIES" > "$TMP/DEPENDENCIES"

mv "$TMP/DEPENDENCIES" "$DEPENDENCIES"
git diff "$DEPENDENCIES"
